### PR TITLE
Allows specifying resource names in the start up configuration

### PR DESCRIPTION
**Pull request by pedromss**
This PR aims to allow diffy deployments to specify resource names in the startup options instead of the `Canonical-Resource` header. The new parameter is optional and the header still takes precedence over the startup configuration.

This allows for resource naming in the UI to be set during deployment and not changed, also not forcing clients to make requests with an additional header.

Could use guidance with:
- Documentation, where should it be added
- Testing, would you like me to add tests to `HttpLifterSpec` for this?

### CODE REVIEW

**Comment by puneetkhanduri** [comment]
Thanks for the pull request. I like the idea and want to make this slightly more ambitious proposal.

Your current implementation is limited to static path structures while most applications use path parameters like `/users/:userid/transactions/:trasactionid/amount`. 

Please take a look at [this implementation](https://github.com/twitter/finatra/blob/5f293844bb8aa8cc638f869bf739878e3de372d5/http/src/main/scala/com/twitter/finatra/http/internal/routing/PathPattern.scala) of PathPattern.

You can use a similar implementation to find matching path names for each request. This would make the solution useful for all Diffy http users.

**Comment by pedromss** [comment]
@puneetkhanduri can you recomend one implementation that I can use (i.e. not private in another artifact) as to avoid copy pasting the one you linked?

**Comment by puneetkhanduri** [comment]
Unfortunately, no. I think writing something similar to this might be the fastest way forward.

**Comment by pedromss** [comment]
@puneetkhanduri please take another look :)

**Pull request merged**
